# Generated by Django 4.0.3 on 2022-06-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accountNumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phoneNumber',
        ),
    ]
